[package]
name = "bitbar-wurstmineberg-status"
version = "2.0.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
base64 = "0.11"
chrono = "0.4"
css-color-parser = "0.1.2"
derive_more = "0.99"
image = "0.22.2"
mime = "*"
notify-rust = "3"
num-traits = "*"
serde_json = "1"
serenity = "0.7"
xdg-basedir = "1"

[dependencies.bitbar]
version = "0.3.1"
features = ["base64"]

[dependencies.reqwest]
version = "0.10"
features = ["blocking", "json"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.timespec]
git = "https://github.com/fenhl/rust-timespec"

[dependencies.url]
version = "2"
features = ["serde"]
